# Generated by Django 6.0.6 on 2026-07-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=127, unique=True)),
                ('product', models.CharField(max_length=127)),
                ('granel', models.CharField(blank=True, max_length=127, null=True)),
                ('bag', models.CharField(blank=True, max_length=127, null=True)),
                ('pallet', models.CharField(blank=True, max_length=127, null=True)),
                ('driver', models.CharField(max_length=127)),
                ('cpf', models.CharField(max_length=127)),
                ('cellphone', models.CharField(max_length=127)),
                ('type', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='companies.company')),
            ],
        ),
    ]
