# Generated by Django 6.0.6 on 2026-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='cargo_type',
            field=models.CharField(default='Bag', max_length=127),
            preserve_default=False,
        ),
    ]
