# Generated by Django 6.0.6 on 2026-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truck_cargo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='granel',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='pallet',
        ),
        migrations.AlterField(
            model_name='truck',
            name='cargo_type',
            field=models.CharField(choices=[('Granel', 'Granel'), ('Bag', 'Bag'), ('Pallet', 'Pallet')], max_length=127),
        ),
    ]
