# Generated by Django 6.0.6 on 2026-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPANY', 'Company'), ('OPERATOR', 'Operator'), ('VIEWER', 'Viewer')], default='COMPANY', max_length=20),
        ),
    ]
