# Generated by Django 6.0.6 on 2026-07-10 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('STANDBY', 'Standby'), ('INSIDE', 'Inside'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('job', models.CharField(choices=[('Carga', 'Carga'), ('Descarga', 'Descarga')], max_length=127)),
                ('on_standby_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_order', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='truck_photos/')),
                ('company_name', models.CharField(blank=True, max_length=127, null=True)),
                ('truck_plate', models.CharField(max_length=127)),
                ('truck_product', models.CharField(max_length=127)),
                ('truck_granel', models.CharField(blank=True, max_length=127, null=True)),
                ('truck_bag', models.CharField(blank=True, max_length=127, null=True)),
                ('truck_pallet', models.CharField(blank=True, max_length=127, null=True)),
                ('truck_driver', models.CharField(max_length=127)),
                ('truck_cpf', models.CharField(max_length=127)),
                ('truck_cellphone', models.CharField(max_length=127)),
                ('truck_type', models.CharField(max_length=127)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='areas.area')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queue_order', '-created_at'],
            },
        ),
    ]
