# Generated by Django 6.0.6 on 2026-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_entries', '0002_queueentry_truck_cargo_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueentry',
            old_name='on_standby_time',
            new_name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='truck_bag',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='truck_granel',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='truck_pallet',
        ),
        migrations.AddField(
            model_name='queueentry',
            name='awaiting_conclusion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='job',
            field=models.CharField(blank=True, choices=[('Carga', 'Carga'), ('Descarga', 'Descarga')], max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ON_YARD', 'On Yard'), ('IN_OPERATION', 'In Operation'), ('AWAITING_CONCLUSION', 'Awaiting Conclusion'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='truck_cargo_type',
            field=models.CharField(choices=[('Granel', 'Granel'), ('Bag', 'Bag'), ('Pallet', 'Pallet')], max_length=127),
        ),
    ]
