# Generated by Django 6.0.6 on 2026-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_entries', '0003_rename_on_standby_time_queueentry_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='document_photos/'),
        ),
    ]
