# Generated by Django 6.0.6 on 2026-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_entries', '0004_queueentry_document_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='document_files/'),
        ),
    ]
